### ISSUE TITLE
JavaScriptファイルの多言語化

### ISSUE THREAD

**Issue by yukimunet** [codeforkanazawa-org/5374site#11]
1. javascripts/csv_to_map.js の中で使用されている日本語をローカライズする。
2. localizable/csv_to_map.js.erbとして配置する。

懸念事項
- all.jsに組み込まれるか。
- minifyする際にminifyの対象となるか。

**Comment by yukimunet** [comment]
単純にやっただけではall.jsに入らなかった。

**Comment by 50river** [comment]
CSVの場所を変更しました。
あとはjs内の記述を多言語化ファイルに対応した形に書き直す必要があります。

**Comment by yukimunet** [comment]
案1. sprintf
https://github.com/alexei/sprintf.js
"<p>%sに<a href=¥"%s¥">%s版5374</a>が作成されました。</p>"

案2. label使えそうなの探す。
"<p>:dateに<a href=¥":url¥">:name版5374</a>が作成されました。</p>"

案2の方がローカライズする人は分かりやすい。

**Comment by yukimunet** [comment]
Aタグがそのまま反映されてしまいましたが、雰囲気的には伝わると思います。

**Comment by yukimunet** [comment]
上記のsprintfで名前付けられる機能があったのでそれでやりました。
en.ymlは未記入。

**Comment by 50river** [comment]
en.yml終了
