### ISSUE TITLE
更新情報をタップした際のページ内遷移がずれる

### ISSUE THREAD

**Issue by yukimunet** [codeforkanazawa-org/5374site#14]
更新情報をタップした際、更新情報のエリアがページのトップにスクロールされるはずだが、されない。
環境：Mac/Chrome&Safari

**Comment by 50river** [comment]
更新情報を開くときに、上のdivを閉じるようになってるから閉じた分だけ上に行ってしまうんやね....連動しないようにすれば上がらなくはなる
さて、どうしましょうか？？？

**Comment by yukimunet** [comment]
それは「bootstrapのせい」？

**Comment by 50river** [comment]
YES
大くくりで同じアコーディオン内にまとめなきゃ
勝手に閉じる事はない。

**Comment by yukimunet** [comment]
アコーディオンが開いた後にスクロールするようにしてみました。
違和感は多少ある。

**Comment by 50river** [comment]
とりあえずはこれで、OKにしとくか！
なんか、もはやアコーディオンが必要なのか疑問な感じw

**Comment by yukimunet** [comment]
> なんか、もはやアコーディオンが必要なのか疑問な感じw
> 確かにそうやわ。5件なら出しておいてもいいかも。
