### ISSUE TITLE
英語ページからの日本語ページヘのリンク

### ISSUE THREAD

**Issue by yuki2006** [codeforkanazawa-org/5374site#15]
https://github.com/50river/5374site/blob/master/locales/en.yml

translate: '<a href="/index.html">日本語</a>'
となっておりますが、

translate: '<a href="../index.html">日本語</a>'
としてないのにはなにか理由がありますか？

後者だと、どこのURLにおいても大丈夫だと思うのですが。

**Comment by 50river** [comment]
？？？？
どうなってるか、読めない

**Comment by 50river** [comment]
../これねOKOK

**Comment by 50river** [comment]
現状enも飛べてなくない？

**Comment by 50river** [comment]
修正完了
