### ISSUE TITLE
cssのリファクタリング

### ISSUE THREAD

**Issue by jshimazu** [codeforkanazawa-org/5374site#16]

**Comment by jshimazu** [comment]
まだ途中ですが、_variable.cssに固定値とカラーコードを集約していきます。
あとは_all.cssの冗長になっているところをsassの機能使ってまとめているところです。

**Comment by 50river** [comment]
:thumbsup:

**Comment by jshimazu** [comment]
_variable.css → 変数定義用
_all.css → 通常のスタイル
_bootstrap-override.scss → bootstrapのスタイル打ち消し
_responsive-desktop.scss → PCビュースタイル
_googlemap.scss → googleMAP API内で使用するスタイル

という感じに分離しました。
_all.cssはsassの構文使って少し見やすくなったと思います！

**Comment by 50river** [comment]
めっちゃ見やすくなったね！
