### ISSUE TITLE
googleMAP API key

### ISSUE THREAD

**Issue by 50river** [codeforkanazawa-org/5374site#19]
所有者変更に伴い、googlemapのAPI keyの変更をお願いします。

**Comment by yuki2006** [comment]
対象のホスト名は

codeforkanazawa-org.github.io/5374site
5374.jp
で大丈夫ですか？

変更するのは大丈夫なのですが、GoogleMAP APIの管理が自分なのですが、
（将来的に変更する場合、僕しか出来ないので）
CfKとして管理した方がいいと思うのですがいかがでしょうか？

**Comment by 50river** [comment]
その二つがあれば大丈夫だと思う。
管理に関しては、CfKのgoogleアカウントへお願いします。

**Comment by yuki2006** [comment]
APIキーをCfKのgoogleアカウントへ移行しました。
