### ISSUE TITLE
デザインをあてる

### ISSUE THREAD

**Issue by 50river** [codeforkanazawa-org/5374site#3]
使っていないBootstrapを削り
改変が必要な部分のCSSをあてる

**Comment by jshimazu** [comment]
＞Bootstrapの削り
http://qiita.com/masamitsu-konya/items/e3630046774ac1fbd346
このあたり参考にして、列挙したコンポーネントをコメントアウトしていく形にしました

**Comment by 50river** [comment]
いいっすね！あとは、画像ですね...
ぶっちゃけ、元のデザインを
そのまま行こうとすると大変なのでちょっとデザイン別にしたほうが良いかもしれません。

**Comment by jshimazu** [comment]
とりあえず生のCSS追記して元のデザインに寄せてあります。
これをsassでうまいこと整頓できないか検討中です
あとはPCビューの場合の見た目調整・・・

**Comment by 50river** [comment]
そやね...無難にやるならmediaQueryで、仕切ってPCの時は画像サイズの上限作って調整かなぁ
