### ISSUE TITLE
リスト内の多言語化

### ISSUE THREAD

**Issue by 50river** [codeforkanazawa-org/5374site#8]
多言語化に伴い、都道府県名を参照しているJSでは上手くいかなくなった。

**Comment by yukimunet** [comment]
編集ファイルはcsvのままでいいと思うので、TravisCIで各言語向けのjsonに変換して、それを読み込むのがいいのではないでしょうか。
もしくは、ajaxではなく、htmlに埋め込んでしまうとか。

**Comment by yuki2006** [comment]
> TravisCIで各言語向けのjsonに変換して
> htmlに埋め込んでしまうとか。

これらのツールは、よくご存じないのですが、どうやったら出来そうでしょうか？

**Comment by yukimunet** [comment]
TravisCIじゃなくてmiddlemanの役割かも。
https://middlemanapp.com/jp/advanced/custom_extensions/

結果、config.rb の activate :minify_javascript みたく、activate :generate_area_json のように使うもよう。

**Comment by 50river** [comment]
こいつで全体を管理できれば良いんだけどね。
ちなみに、この番号順で都道府県は並べてあります。
データ作成者は、自分の町の番号を追記してもらうと作業捗ると思うよ。
http://www.tt.rim.or.jp/~ishato/tiri/code/code.htm

**Comment by yukimunet** [comment]
1. 市町村コードに対応した名称のyamlを作成する。
2. csvには市町村コードを記載する（メモとして日本語も入れておいてもいいかもしれない）。
3. build時にcsvを元にerbにselectのoptionを展開する。
4. 1のyamlでローカライズされる。

selectのみ考えたけど、mapも同様にbuild時にコードを生成した方がよいのかも。

**Comment by yuki2006** [comment]
とりあえずプルリクお待ちしておりますのでよろしくお願い致します

**Comment by yuki2006** [comment]
ちなみに、全国地方公共団体コード仕様は正式には6桁です。
http://www.soumu.go.jp/main_content/000137948.pdf
（ただし6桁目はチェックディジットなので、有向な桁数的には5桁ですが）

全国地方公共団体コードを使うなら、
（正式な）6桁を使うか、5桁を使うか決める必要があると思います。

**Comment by 50river** [comment]
6桁にするか！
明日、ちょっとデータ入れるところの雛形考えてみるわ！
