### ISSUE TITLE
マーカーのInfoWindowが複数表示される。

### ISSUE THREAD

**Issue by yukimunet** [codeforkanazawa-org/5374site#9]
マーカーをタップして、InfoWindowを表示した後、他のマーカーをタップすると、新たなInfoWindowが表示される。
InfoWindowは１つのみで良いかもしれません。
参考URL
http://waox.main.jp/news/?p=1116

**Comment by yuki2006** [comment]
ありがとうございます。
そうしたいと思います。

**Comment by yukimunet** [comment]
再修正完了。
